name: Upload source maps to Datadog
description: >-
  Upload your source maps to Datadog to de-obfuscate your different stack traces.
  For any given error, you can access the file path, line number, and code snippet
  for each frame of the related stack trace.
# ENV needed:
# DATADOG_API_KEY - Dedicated Datadog API key, export it as an environment variable

inputs:
  version:
    description: Used to match the version tag set on the RUM SDK
    type: string
    required: true
  service_name:
    description: Set as the name of the service you're uploading sourcemaps for
    type: string
    required: true
  path:
    description: Directory in which sourcemaps are located
    type: string
    required: true
  prefix:
    description: Prefix common to all your JS source files, depending on the URL they are served from
    type: string
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check if DATADOG_API_KEY defined
      shell: bash
      if: "${{ env.DATADOG_API_KEY == '' }}"
      run: |
        echo env variable DATADOG_API_KEY must be defined
        exit 1
    - name: Set environment variables
      shell: bash
      run: |
        if [[ ${{ env.DATADOG_SITE == '' }} ]]; then
          echo "DATADOG_SITE=datadoghq.eu" >> $GITHUB_ENV
        fi
        if [[ ${{ env.DATADOG_API_HOST == '' }} ]]; then
          echo "DATADOG_API_HOST=api.datadoghq.eu" >> $GITHUB_ENV
        fi
    - uses: actions/download-artifact@v3
      name: Download artifact
      with:
        name: playtomic-manager-react-app-staging-${{ inputs.version }}
    - name: show files0
      shell: bash
      run: |
        ls
    - name: Unzip artifact
      shell: bash
      run: unzip playtomic-manager-react-app-staging-${{ inputs.version }}.zip
    - name: show files
      shell: bash
      run: |
        ls
    - name: show files 2
      shell: bash
      run: |
        ls build
    - name: show files 3
      shell: bash
      run: |
        ls build/static/js
    - name: Upload sourcemaps
      env:
        DATADOG_SITE: ${{ env.DATADOG_SITE }}
        DATADOG_API_HOST: ${{ env.DATADOG_API_HOST }}
      shell: bash
      run: |
        npx @datadog/datadog-ci@1.7.2 sourcemaps upload ${{ inputs.path }} \
        --service=${{ inputs.service_name }} \
        --release-version=${{ inputs.version }} \
        --minified-path-prefix=${{ inputs.prefix }}
